//
// Created by krzysztof on 21.01.2022.
//

#ifndef TOKENMISPLACEDALGORITHM_MESSAGETYPE_H
#define TOKENMISPLACEDALGORITHM_MESSAGETYPE_H

enum MessageType {
    TOKEN, REC_TOKEN, ACK
};

#endif //TOKENMISPLACEDALGORITHM_MESSAGETYPE_H
